# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11)),
                ('itemId', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=1)),
                ('finalFee', models.CharField(max_length=10)),
                ('vcode', models.CharField(max_length=200)),
                ('vcodePass', models.CharField(max_length=200)),
            ],
        ),
    ]
